#!/bin/bash

# Java进程列出脚本

# 先让环境变量生效
source /etc/profile

# 临时密码文件还存在就说明SSH公钥还没交换完毕，需要等待交换完毕
while [ -e $TEMP_PASS_FILE ]; do
    sleep 3
done

echo "Listing Java Processes..."

for host in $SH_HOSTS; do
    echo ============= jps on $host ==========
    ssh root@$host /opt/bitnami/java/bin/jps
done
